FreshFoodHTH/FreshFoodHTH/Areas/Admin/Controllers/NguoiDungAdminController.cs
using FreshFoodHTH.Common;
using FreshFoodHTH.Models.DAO.Admin;
using FreshFoodHTH.Models.EF;
using FreshFoodHTH.Models.EFplus;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FreshFoodHTH.Areas.Admin.Controllers
{
    public class NguoiDungAdminController : BaseController
    {
        // GET: Admin/NguoiDungAdmin
        FreshFoodDBContext db = new FreshFoodDBContext();
        NguoiDungDAO ndDao = new NguoiDungDAO();

        public ActionResult Index(int? page, int? PageSize, string searching = "")
        {
            ViewBag.SearchString = searching;
            ViewBag.PageSize = new List<SelectListItem>()
            {
                new SelectListItem() { Value="10", Text= "10" },
                new SelectListItem() { Value="15", Text= "15" },
                new SelectListItem() { Value="20", Text= "20" },
                new SelectListItem() { Value="25", Text= "25" },
                new SelectListItem() { Value="50", Text= "50" }
            };
            int pageNumber = (page ?? 1);
            int pagesize = (PageSize ?? 10);
            ViewBag.psize = pagesize;
            ViewBag.Count = ndDao.ListAdminSimple(searching).Count();
            return View(ndDao.ListAdminSimpleSearch(pageNumber, pagesize, searching));
        }

        public ActionResult Details(Guid id)
        {
            NguoiDung nguoidung = ndDao.GetByID(id);
            return View(nguoidung);
        }

        public ActionResult ChangePassword(Guid id)
        {
            flatChangePassword obj = new flatChangePassword() { IDUser = id, Username = (ndDao.GetByID(id)).Username };
            return View(obj);
        }

        [HttpPost]
        public ActionResult ChangePassword(Guid id, string oldpass, string newpass, string confirm)
        {
            NguoiDung nguoidung = ndDao.GetByID(id);
            flatChangePassword userchange = new flatChangePassword() { IDUser = id, Username = (ndDao.GetByID(id)).Username, OldPass = oldpass, NewPass = newpass, Confirm = confirm };

            nguoidung.ModifiedDate = DateTime.Now;
            nguoidung.ModifiedBy = (string)Session["USERNAME_SESSION"];


            if (ModelState.IsValid)
            {
                if (BCrypt.Net.BCrypt.Verify(oldpass, nguoidung.Password))
                {
                    ViewBag.OldPassword = string.Empty;
                    if (BCrypt.Net.BCrypt.Verify(newpass, nguoidung.Password))
                        ViewBag.NewPassword = "** Mật khẩu mới phải khác mật khẩu cũ";
                    else
                    {
                        ViewBag.NewPassword = string.Empty;
                        if (!newpass.Equals(confirm))
                            ViewBag.ConfirmPassword = "** Mật khẩu mới và xác nhận mật khẩu không khớp";
                        else
                        {
                            ViewBag.ConfirmPassword = string.Empty;
                            ndDao.ChangePassword(nguoidung, newpass);
                            return RedirectToAction("Details", new { id = nguoidung.IDNguoiDung });
                        }
                    }
                    return View(userchange);
                }
                ViewBag.OldPassword = "** Mật khẩu cũ không đúng";
                return View(userchange);
            }
            else
            {
                return View(userchange);
            }
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(string username, string password, string confirm, string ten, string dienthoai, string email, string diachi, HttpPostedFileBase avatar)
        {
            NguoiDung nguoidung = new NguoiDung();
            flatNguoiDungMoi newuser = new flatNguoiDungMoi() { Username = username, Ten = ten, DienThoai = dienthoai, DiaChi = diachi, Password = password, Confirm = confirm };

            nguoidung.IDNguoiDung = Guid.NewGuid();
            nguoidung.IsAdmin = true;
            nguoidung.IDLoaiNguoiDung = db.LoaiNguoiDungs.Where(x => x.Ten.Equals("Admin")).Select(x => x.IDLoaiNguoiDung).ToList().ElementAt(0);
            nguoidung.Username = username;
            nguoidung.Ten = ten;
            nguoidung.DienThoai = dienthoai;
            nguoidung.Email = email;
            nguoidung.DiaChi = diachi;

            nguoidung.CreatedDate = DateTime.Now;
            nguoidung.CreatedBy = (string)Session["USERNAME_SESSION"];
            nguoidung.ModifiedDate = DateTime.Now;
            nguoidung.ModifiedBy = (string)Session["USERNAME_SESSION"];

            if (ModelState.IsValid)
            {
                if (!password.Equals(confirm))
                {
                    ViewBag.ConfirmNewPassword = "** Mật khẩu và xác nhận mật khẩu không khớp";
                    return View(newuser);
                }

                nguoidung.Password = BCrypt.Net.BCrypt.HashPassword(password);
                
                if (avatar != null && avatar.ContentLength > 0)
                {
                    var path = Path.Combine(Server.MapPath("~/Areas/Admin/Content/Photos/"), System.IO.Path.GetFileName(avatar.FileName));
                    avatar.SaveAs(path);
                    nguoidung.Avatar = avatar.FileName;
                }
                ndDao.Add(nguoidung);
                return RedirectToAction("Index");
            }
            else
            {
                return View(newuser);
            }
        }

        public ActionResult Edit(Guid id)
        {
            return View(ndDao.GetByID(id));
        }

        [HttpPost]
        public ActionResult Edit(Guid id, string ten, string dienthoai, string email, string diachi, HttpPostedFileBase avatar)
        {
            NguoiDung nguoidung = ndDao.GetByID(id);
            nguoidung.Ten = ten;
            nguoidung.DienThoai = dienthoai;
            nguoidung.Email = email;
            nguoidung.DiaChi = diachi;

            nguoidung.ModifiedDate = DateTime.Now;
            nguoidung.ModifiedBy = (string)Session["USERNAME_SESSION"];

            if (ModelState.IsValid)
            {
                if (avatar != null && avatar.ContentLength > 0)
                {
                    var path = Path.Combine(Server.MapPath("~/Areas/Admin/Content/Photos/"), System.IO.Path.GetFileName(avatar.FileName));
                    avatar.SaveAs(path);
                    nguoidung.Avatar = avatar.FileName;
                }
                ndDao.Edit(nguoidung);
                return RedirectToAction("Index");
            }
            else
            {
                return View(nguoidung);
            }
        }

        public ActionResult Delete(Guid id)
        {
            ndDao.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

FreshFoodHTH/FreshFoodHTH/Areas/Admin/Views/NguoiDungAdmin/ChangePassword.cshtml
@model FreshFoodHTH.Models.EFplus.flatChangePassword

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section header
{
    Người dùng - Đổi mật khẩu ( @Model.Username )
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDUser)

        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Mật khẩu cũ</label>
                <input type="password" class="form-control" name="oldpass" placeholder="Nhập mật khẩu cũ ..." value=" @Html.DisplayFor(model => model.OldPass)" required>
                <p style="font-size:15px; color:red; font-style:italic"><b>@ViewBag.OldPassword</b></p>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Mật khẩu mới</label>
                <input type="password" class="form-control" name="newpass" placeholder="Nhập mật khẩu mới ..." value=" @Html.DisplayFor(model => model.NewPass)" required>
                <p style="font-size:15px; color:red; font-style:italic"><b>@ViewBag.NewPassword</b></p>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Xác nhận mật khẩu</label>
                <input type="password" class="form-control" name="confirm" placeholder="Xác nhận mật khẩu ..." value=" @Html.DisplayFor(model => model.Confirm)" required>
                <p style="font-size:15px; color:red; font-style:italic"><b>@ViewBag.ConfirmPassword</b></p>
            </div>
        </div>


        <button type="submit" class="btn btn-primary" style="width:110px">
            <a class="fa fa-save"></a> &nbsp;Lưu lại
        </button>
        <button type="button" class="btn btn-warning" style="width:110px">
            <a class="fa fa-arrow-left"></a> &nbsp;
            @Html.ActionLink("Trở về", "Details", new { id = Model.IDUser })
        </button>
    </div>
}

FreshFoodHTH/FreshFoodHTH/Areas/Admin/Views/NguoiDungAdmin/Create.cshtml
@model FreshFoodHTH.Models.EFplus.flatNguoiDungMoi

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section header
{
    Người dùng - Thêm người dùng
}

@using (Html.BeginForm("Create", "NguoiDungAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Username</label>
                <input type="text" class="form-control" name="username" placeholder="Nhập username ..." value=" @Html.DisplayFor(model => model.Username)" required>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Tên </label>
                <input type="text" class="form-control" name="ten" placeholder="Nhập tên ..." value=" @Html.DisplayFor(model => model.Ten)" required>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Điện thoại</label>
                <input type="text" class="form-control" name="dienthoai" placeholder="Nhập số điện thoại ..." value=" @Html.DisplayFor(model => model.DienThoai)" required>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Email</label>
                <input type="text" class="form-control" name="email" placeholder="Nhập email ..." value=" @Html.DisplayFor(model => model.Email)" required>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Địa chỉ</label>
                <input type="text" class="form-control" name="diachi" placeholder="Nhập địa chỉ ..." value=" @Html.DisplayFor(model => model.DiaChi)" required>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputFile">Hình đại diện</label>
                <input type="file" id="avatar" name="avatar" required>
            </div>
        </div>

        <hr />
        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Mật khẩu</label>
                <input type="password" class="form-control" name="password" placeholder="Nhập mật khẩu ..." value=" @Html.DisplayFor(model => model.Password)" required>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Xác nhận mật khẩu</label>
                <input type="password" class="form-control" name="confirm" placeholder="Xác nhận mật khẩu ..." value=" @Html.DisplayFor(model => model.Confirm)" required>
                <p style="font-size:15px; color:red; font-style:italic"><b>@ViewBag.ConfirmNewPassword</b></p>
            </div>
        </div>

        <button type="submit" class="btn btn-primary" style="width:110px">
            <a class="fa fa-save"></a> &nbsp;Lưu lại
        </button>
        <button type="button" class="btn btn-warning" style="width:110px">
            <a class="fa fa-th-list"></a> &nbsp;
            @Html.ActionLink("Danh sách", "Index")
        </button>
    </div>
}

FreshFoodHTH/FreshFoodHTH/Areas/Admin/Views/NguoiDungAdmin/Details.cshtml
@model FreshFoodHTH.Models.EF.NguoiDung

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section header
{
    Người dùng - Thông tin người dùng ( @Model.Username )
}

<div>
    <table style="width:60%">
        <td style="vertical-align:top">
            <div class="form-group">
                <div class="col-md-10">
                    <img height="150" width="150" src="~/Areas/Admin/Content/Photos/@Model.Avatar" alt="Chưa có" style="border:solid 1px gray; border-radius:10px" />
                </div>
            </div>
        </td>
        <td style="vertical-align:top">
            <dl class="dl-horizontal">
                <dt>
                    Username:
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Username)
                </dd>
                <dt>
                    Tên:
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Ten)
                </dd>
                <dt>
                    Điện thoại:
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DienThoai)
                </dd>
                <dt>
                    Email:
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Email)
                </dd>
                <dt>
                    Địa chỉ:
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DiaChi)
                </dd>
                <dt>
                    Ngày tạo:
                </dt>

                <dd>
                    @Html.Raw(Convert.ToDateTime(Model.CreatedDate).ToString("dd/MM/yyyy"))
                </dd>
                <dt>
                    Ngày cập nhật:
                </dt>

                <dd>
                    @Html.Raw(Convert.ToDateTime(Model.ModifiedDate).ToString("dd/MM/yyyy"))
                </dd>
            </dl>
        </td>
    </table>
</div>

<br />

<button type="button" class="btn btn-primary btn-admin">
    <a class="fa fa-edit"></a> &nbsp;
    @Html.ActionLink("Chỉnh sửa", "Edit", new { id = Model.IDNguoiDung })
</button>
@if (Model.Username.Equals(Session["USERNAME_SESSION"]))
{
    <button type="button" class="btn btn-success btn-admin">
        <a class="fa fa-key"></a> &nbsp;
        @Html.ActionLink("Đổi mật khẩu", "ChangePassword", new { id = Model.IDNguoiDung })
    </button>
}
<button type="button" class="btn btn-warning btn-admin">
    <a class="fa fa-th-list"></a> &nbsp;
    @Html.ActionLink("Danh sách", "Index")
</button>

FreshFoodHTH/FreshFoodHTH/Areas/Admin/Views/NguoiDungAdmin/Edit.cshtml
@model FreshFoodHTH.Models.EF.NguoiDung

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section header
{
    Người dùng - Chỉnh sửa thông tin ( @Model.Username )
}

@using (Html.BeginForm("Edit", "NguoiDungAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDNguoiDung)

        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Tên </label>
                <input type="text" class="form-control" name="ten" placeholder="Nhập tên ..." value=" @Html.DisplayFor(model => model.Ten)" required>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Điện thoại</label>
                <input type="text" class="form-control" name="dienthoai" placeholder="Nhập số điện thoại ..." value=" @Html.DisplayFor(model => model.DienThoai)" required>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Email</label>
                <input type="text" class="form-control" name="email" placeholder="Nhập email ..." value=" @Html.DisplayFor(model => model.Email)" required>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Địa chỉ</label>
                <input type="text" class="form-control" name="diachi" placeholder="Nhập địa chỉ ..." value=" @Html.DisplayFor(model => model.DiaChi)" required>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputFile">Hình đại diện</label>
                <input type="file" id="avatar" name="avatar">
            </div>
        </div>


        <button type="submit" class="btn btn-primary btn-admin" style="width:110px">
            <a class="fa fa-save"></a> &nbsp;Lưu lại
        </button>
        <button type="button" class="btn btn-warning btn-admin" style="width:110px">
            <a class="fa fa-th-list"></a> &nbsp;
            @Html.ActionLink("Danh sách", "Index")
        </button>
    </div>
}

FreshFoodHTH/FreshFoodHTH/Areas/Admin/Views/NguoiDungAdmin/Index.cshtml
@model PagedList.IPagedList<FreshFoodHTH.Models.EF.NguoiDung>
@using PagedList.Mvc

@{ ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";

    int i;
    if (Model.Count == ViewBag.psize)
    {
        i = Model.PageNumber * Model.Count - Model.Count;
    }
    else
    {
        i = ViewBag.Count - Model.Count;
    }

    string GetSTT()
    {
        i++;
        return Convert.ToString(i);
    } }

@section header
{
    Danh sách Người dùng
}

<table style="width:100%; margin-bottom:10px">
    <tr>
        <td>
            @using (Html.BeginForm("Index", "NguoiDungAdmin", FormMethod.Get, new { id = "form1" }))
            {
<p style="float:left; color:navy; height:32px"><b>Hiển thị &nbsp; </b>@Html.DropDownList("pageSize") &nbsp; <b>bản ghi / trang </b> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>

                <input type="text" name="searching" value="@ViewBag.SearchString" placeholder="Nhập thông tin tìm kiếm ..." style="width: 400px;" />
                                <input type="submit" value="Tìm kiếm" />}
        </td>
        <td>
            <button type="button" class="btn btn-success btn-admin" style="margin-bottom:10px; margin-left:5px; float: right; width:110px">
                <i class="fa fa-plus-square"></i> &nbsp;
                @Html.ActionLink("Thêm mới", "Create", "NguoiDungAdmin")
            </button>
        </td>
    </tr>
</table>

<table id="example1" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>STT</th>
            <th>Username</th>
            <th>Tên</th>
            <th>Hình đại diện</th>
            <th>Ngày cập nhật</th>
            <th>Chức năng</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
<tr>
    <td>
        @Html.Raw(GetSTT())
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Username)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Ten)
    </td>
    <td>
        <img height="20" width="30" src="~/Areas/Admin/Content/Photos/@item.Avatar" alt="Chưa có" style="border: solid 1px #80808038" />
    </td>
    <td>
        @Html.Raw(@Convert.ToDateTime(item.ModifiedDate).ToString("dd/MM/yyyy"))
    </td>
    <td>
        <i class="fa fa-info-circle"></i> &nbsp;
        @Html.ActionLink("Xem", "Details", new { id = item.IDNguoiDung }) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <i class="fa fa-edit"></i> &nbsp;
        @Html.ActionLink("Sửa", "Edit", new { id = item.IDNguoiDung }) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <i class="fa fa-trash"></i> &nbsp;
        @Html.ActionLink("Xóa", "Delete", new { id = item.IDNguoiDung }, new { onclick = "return confirm('Chắc chắn muốn xoá?');" })
    </td>
</tr>
}
    </tbody>
</table>


@using (Html.BeginForm("Index", "NguoiDungAdmin", FormMethod.Get, new { id = "form1" }))
{
<div class="pager">
    <table style="width:100%">
        <col style="width:50%">
        <col style="width:50%">
        <tr>
            <td style="float:left">
                <b style="color:navy">
                    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount &nbsp;&nbsp;-&nbsp;&nbsp;
                    @if (Model.Count == ViewBag.psize)
                    {
    <span>Đang hiển thị (@(((Model.PageNumber * Model.Count) - Model.Count) + 1)-@(Model.PageNumber * Model.Count)) / @ViewBag.Count</span> }
else
{
<span>Đang hiển thị (@((ViewBag.Count - Model.Count) + 1)-@(ViewBag.Count)) / @ViewBag.Count</span>}
                </b>
            </td>
            <td style="float:right; margin-top:-20px">
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page, pageSize = ViewBag.psize, @searching = @ViewBag.SearchString }))
            </td>
        </tr>
    </table>
</div>}
<script src="~/Assets/Admin/LTE/plugins/jQuery/jQuery-2.1.4.min.js" type="text/javascript"></script>
<script>
    $(document).ready(function () {
        $("#checkAll").click(function () {
            if (this.checked) {
                $(".chkbox").prop('checked', $(this).prop('checked', true));
            }
            else {
                $('.chkbox').each(function () { this.checked = false; });
            }
        });
        $('.chkbox').on('click', function () {
            if ($('.chkbox:checked').length == $('.chkbox').length) {
                $('#checkAll').prop('checked', true);
            } else {
                $('#checkAll').prop('checked', false);
            }
        });
    });</script>
<script type="text/javascript">
    $(function () {
        $("#pageSize").change(function () {
            $("#form1").submit();
        });
    });</script>

FreshFoodHTH/FreshFoodHTH/Areas/Admin/Views/NguoiDungAdmin/IndexChiTietGioHang.cshtml
@model IEnumerable<FreshFoodHTH.Models.EF.ChiTietGioHang>


<table id="example1" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                Khách hàng
            </th>
            <th>
                Sản phẩm
            </th>
            <th>
                Số lượng
            </th>
            <th>
                Thành tiền
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NguoiDung.Ten)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SanPham.Ten)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SoLuong)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ThanhTien)
                </td>
                @*<td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.IDChiTietGioHang }) |
                    @Html.ActionLink("Details", "Details", new { id=item.IDChiTietGioHang }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.IDChiTietGioHang })
                </td>*@
            </tr>
        }
    </tbody>
</table>